adding archive/v196 files

diff --git a/bin/steps/python b/bin/steps/python
--- a/bin/steps/python
+++ b/bin/steps/python
@@ -1,92 +1,90 @@
 #!/usr/bin/env bash
 
-# TODO: Replace runtime-fixer with a bash equivalent, since currently on rebuilds it
-# gets run with the cached Python install (rather than system Python), which means it
-# fails to run with glibc errors on stack downgrades (see spec/hatchet/stack_spec.rb).
-# To work around this for now, non-zero exit codes are ignored (most runtime.txt files
-# don't need fixing up, so the script not running won't normally matter).
-runtime-fixer runtime.txt || true
+set +e
+runtime-fixer runtime.txt
 PYTHON_VERSION=$(cat runtime.txt)
 
 # The location of the pre-compiled python binary.
-PYTHON_URL="${S3_BASE_URL}/${STACK}/runtimes/${PYTHON_VERSION}.tar.gz"
+VENDORED_PYTHON="${S3_BASE_URL}/${STACK}/runtimes/${PYTHON_VERSION}.tar.gz"
 
-if ! curl --output /dev/null --silent --head --fail --retry 3 --retry-connrefused --connect-timeout 5 "${PYTHON_URL}"; then
-  puts-warn "Requested runtime '${PYTHON_VERSION}' is not available for this stack (${STACK})."
-  puts-warn "For supported versions, see: https://devcenter.heroku.com/articles/python-support"
+SECURITY_UPDATE="Python has released a security update! Please consider upgrading to"
+SECURITY_UPDATE_PYPY="The PyPy project has released a security update! Please consider upgrading to"
+
+ONLY_SUPPORTED_2_VERSION="Only the latest version of Python 2 is supported on the platform. Please consider upgrading to"
+
+PYTHON_2_EOL_UPDATE="Python 2 has reached its community EOL. Upgrade your Python runtime to maintain a secure application as soon as possible."
+
+# check if runtime exists
+if curl --output /dev/null --silent --head --fail "$VENDORED_PYTHON"; then
+  if [[ "$PYTHON_VERSION" == $PY39* ]]; then
+    if [ "$PYTHON_VERSION" != "$LATEST_39" ]; then
+      puts-warn "$SECURITY_UPDATE" "$LATEST_39"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PY38* ]]; then
+    # do things to alert the user of security release available
+    if [ "$PYTHON_VERSION" != "$LATEST_38" ]; then
+      puts-warn "$SECURITY_UPDATE" "$LATEST_38"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PY37* ]]; then
+    # do things to alert the user of security release available
+    if [ "$PYTHON_VERSION" != "$LATEST_37" ]; then
+      puts-warn "$SECURITY_UPDATE" "$LATEST_37"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PY36* ]]; then
+    # security update note
+    if [ "$PYTHON_VERSION" != "$LATEST_36" ]; then
+      puts-warn "$SECURITY_UPDATE" "$LATEST_36"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PY35* ]]; then
+    # security update note
+    if [ "$PYTHON_VERSION" != "$LATEST_35" ]; then
+      puts-warn "$SECURITY_UPDATE" "$LATEST_35"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PY34* ]]; then
+    # security update note
+    if [ "$PYTHON_VERSION" != "$LATEST_34" ]; then
+      puts-warn "$SECURITY_UPDATE" "$LATEST_34"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PY27* ]]; then
+    puts-warn "$PYTHON_2_EOL_UPDATE"
+    echo "       Learn More: https://devcenter.heroku.com/articles/python-2-7-eol-faq"
+    # security update note
+    if [ "$PYTHON_VERSION" != "$LATEST_27" ]; then
+      puts-warn "$ONLY_SUPPORTED_2_VERSION" "$LATEST_27"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PYPY27* ]]; then
+    # security update note
+    if [ "$PYTHON_VERSION" != "$LATEST_PYPY_27" ]; then
+      puts-warn "$SECURITY_UPDATE_PYPY" "$LATEST_PYPY_27"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+  if [[ "$PYTHON_VERSION" == $PYPY36* ]]; then
+    # security update note
+    if [ "$PYTHON_VERSION" != "$LATEST_PYPY_36" ]; then
+      puts-warn "$SECURITY_UPDATE_PYPY" "$LATEST_PYPY_36"
+      echo "       Learn More: https://devcenter.heroku.com/articles/python-runtimes"
+    fi
+  fi
+else
+  puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
+  puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
   exit 1
 fi
-
-function warn_eol_python_version() {
-  local major_version="${1}"
-  local eol_date="${2}"
-  puts-warn
-  puts-warn "Python ${major_version} reached upstream end-of-life on ${eol_date}, and is"
-  puts-warn "therefore no longer receiving security updates:"
-  puts-warn "https://devguide.python.org/versions/#supported-versions"
-  puts-warn
-  puts-warn "Upgrade to a newer Python version as soon as possible to keep your app secure."
-  puts-warn "See: https://devcenter.heroku.com/articles/python-runtimes"
-  puts-warn
-}
-
-function warn_if_patch_update_available() {
-  local current_version="${1}"
-  local latest_patch_version="${2}"
-  if [[ "${current_version}" != "${latest_patch_version}" ]]; then
-    puts-warn
-    puts-warn "A Python security update is available! Upgrade as soon as possible to: ${latest_patch_version}"
-    puts-warn "See: https://devcenter.heroku.com/articles/python-runtimes"
-    puts-warn
-  fi
-}
-
-case "${PYTHON_VERSION}" in
-  python-3.10.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_310}"
-    ;;
-  python-3.9.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_39}"
-    ;;
-  python-3.8.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_38}"
-    ;;
-  python-3.7.*)
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_37}"
-    ;;
-  python-3.6.*)
-    warn_eol_python_version "3.6" "December 23rd, 2021"
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_36}"
-    ;;
-  python-3.5.*)
-    warn_eol_python_version "3.5" "September 30th, 2020"
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_35}"
-    ;;
-  python-3.4.*)
-    warn_eol_python_version "3.4" "March 18th, 2019"
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_34}"
-    ;;
-  python-2.7.*)
-    puts-warn
-    puts-warn "Python 2 reached upstream end-of-life on January 1st, 2020, and is"
-    puts-warn "therefore no longer receiving security updates. Upgrade to Python 3"
-    puts-warn "as soon as possible to keep your app secure."
-    puts-warn
-    puts-warn "In addition, Python 2 is only supported on our oldest stack, Heroku-18,"
-    puts-warn "which is deprecated and reaches end-of-life on April 30th, 2023."
-    puts-warn
-    puts-warn "See: https://devcenter.heroku.com/articles/python-2-7-eol-faq"
-    puts-warn
-    warn_if_patch_update_available "${PYTHON_VERSION}" "${LATEST_27}"
-    ;;
-  pypy*)
-    puts-warn
-    puts-warn "PyPy support is deprecated and the versions available on Heroku are outdated and insecure."
-    puts-warn "Please switch to one of the supported CPython versions by updating your runtime.txt."
-    puts-warn "See: https://devcenter.heroku.com/articles/python-support"
-    puts-warn
-    ;;
-esac
 
 mcount "version.python.${PYTHON_VERSION}"
 
@@ -104,26 +102,22 @@ if [ -f .heroku/python-version ]; then
   fi
 fi
 
-# If using Pip, check if we should reinstall python dependencies given that requirements.txt
-# is non-deterministic (not all packages pinned, doesn't handle uninstalls etc). We don't need
-# to do this when using Pipenv, since it has a lockfile and syncs the packages for us.
-if [[ -f "${BUILD_DIR}/requirements.txt" ]]; then
-  if [[ ! -f "$CACHE_DIR/.heroku/requirements.txt" ]]; then
-    # This is a the first build of an app (or the build cache was cleared). Since there
-    # are no cached packages, we only need to store the requirements file for next time.
+# Check if we should reinstall python dependencies
+if [[ ! -f "$CACHE_DIR/.heroku/requirements.txt" ]]; then
+  # IF there's no cached dependencies, update cached version of requirements.txt
+  # This should only run for new apps and first deploys after this update
+  cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
+else
+  # IF there IS a cached directory, check for differences with the new one
+  if ! diff "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt" &> /dev/null; then
+    puts-step "Requirements file has been changed, clearing cached dependencies"
+    # if there are any differences, clear the Python cache
+    # Installing Python over again does not take noticably more time
     cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
+    rm -rf .heroku/python
+    unset SKIP_INSTALL
   else
-    # IF there IS a cached directory, check for differences with the new one
-    if ! diff "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt" &> /dev/null; then
-      puts-step "Requirements file has been changed, clearing cached dependencies"
-      # if there are any differences, clear the Python cache
-      # Installing Python over again does not take noticably more time
-      cp -R "$BUILD_DIR/requirements.txt" "$CACHE_DIR/.heroku/requirements.txt"
-      rm -rf .heroku/python
-      unset SKIP_INSTALL
-    else
-      puts-step "No change in requirements detected, installing from cache"
-    fi
+    puts-step "No change in requirements detected, installing from cache"
   fi
 fi
 
@@ -135,10 +129,9 @@ else
   # Prepare destination directory.
   mkdir -p .heroku/python
 
-  if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 5 "${PYTHON_URL}" | tar -zxC .heroku/python; then
-    # The Python version was confirmed to exist previously, so any failure here is due to
-    # a networking issue or archive/buildpack bug rather than the runtime not existing.
-    puts-warn "Failed to download/install ${PYTHON_VERSION}"
+  if ! curl "${VENDORED_PYTHON}" -s | tar zxv -C .heroku/python &> /dev/null; then
+    puts-warn "Requested runtime ($PYTHON_VERSION) is not available for this stack ($STACK)."
+    puts-warn "Aborting.  More info: https://devcenter.heroku.com/articles/python-support"
     exit 1
   fi
 
@@ -149,33 +142,23 @@ else
   hash -r
 fi
 
-PIP_VERSION='22.2.2'
-SETUPTOOLS_VERSION='63.4.3'
-WHEEL_VERSION='0.37.1'
+set -e
 
-case "${PYTHON_VERSION}" in
-  python-3.6.*|pypy3.6-*)
-    # Python 3.6 support was dropped in pip 22+ and setuptools 59.7.0+.
-    PIP_VERSION='21.3.1'
-    SETUPTOOLS_VERSION='59.6.0'
-    ;;
-  python-3.5.*)
-    # Python 3.5 support was dropped in pip 21+ and setuptools 51+.
-    PIP_VERSION='20.3.4'
-    SETUPTOOLS_VERSION='50.3.2'
-    ;;
-  python-3.4.*)
-    # Python 3.4 support was dropped in pip 19.2+, setuptools 44+ and wheel 0.34+.
-    PIP_VERSION='19.1.1'
-    SETUPTOOLS_VERSION='43.0.0'
-    WHEEL_VERSION='0.33.6'
-    ;;
-  python-2.7.*|pypy2.7-*)
-    # Python 2.7 support was dropped in pip 21+ and setuptools 45+.
-    PIP_VERSION='20.3.4'
-    SETUPTOOLS_VERSION='44.1.1'
-    ;;
-esac
+PIP_VERSION='20.2.4'
+# Must use setuptools <47.2.0 until we fix:
+# https://github.com/heroku/heroku-buildpack-python/issues/1006
+SETUPTOOLS_VERSION='47.1.1'
+WHEEL_VERSION='0.36.2'
+
+if [[ "${PYTHON_VERSION}" == ${PY34}* ]]; then
+  # Python 3.4 support was dropped in pip 19.2+, setuptools 44+ and wheel 0.34+.
+  PIP_VERSION='19.1.1'
+  SETUPTOOLS_VERSION='43.0.0'
+  WHEEL_VERSION='0.33.6'
+elif [[ "${PYTHON_VERSION}" == ${PY27}* || "${PYTHON_VERSION}" == ${PYPY27}* ]]; then
+  # Python 2.7 support was dropped in setuptools 45+.
+  SETUPTOOLS_VERSION='44.1.1'
+fi
 
 puts-step "Installing pip ${PIP_VERSION}, setuptools ${SETUPTOOLS_VERSION} and wheel ${WHEEL_VERSION}"
 
@@ -186,18 +169,11 @@ puts-step "Installing pip ${PIP_VERSION}, setuptools ${SETUPTOOLS_VERSION} and w
 #  - we would still have to manage several versions of get-pip.py, to support older Pythons.
 # Instead, we use the pip wheel to install itself, using the method described here:
 # https://github.com/pypa/pip/issues/2351#issuecomment-69994524
-
-PIP_MAJOR_VERSION="${PIP_VERSION%%.*}"
-if [[ "${PIP_MAJOR_VERSION}" -ge 21 ]]; then
-  # Pip 21+ dropped support for Python 2, so no longer uses universal wheels.
-  PIP_WHEEL_FILENAME="pip-${PIP_VERSION}-py3-none-any.whl"
-else
-  PIP_WHEEL_FILENAME="pip-${PIP_VERSION}-py2.py3-none-any.whl"
-fi
+PIP_WHEEL_FILENAME="pip-${PIP_VERSION}-py2.py3-none-any.whl"
 PIP_WHEEL_URL="${S3_BASE_URL}/common/${PIP_WHEEL_FILENAME}"
 PIP_WHEEL="${TMPDIR:-/tmp}/${PIP_WHEEL_FILENAME}"
 
-if ! curl --silent --show-error --fail --retry 3 --retry-connrefused --connect-timeout 5 "${PIP_WHEEL_URL}" -o "$PIP_WHEEL"; then
+if ! curl -sSf "${PIP_WHEEL_URL}" -o "$PIP_WHEEL"; then
   mcount "failure.python.download-pip"
   puts-warn "Failed to download pip"
   exit 1
